### ISSUE TITLE
Update of template

### ISSUE THREAD

**Issue by Trudko** [francodacosta/atom-php-getters-setters#11]
Hi, first of all thank you for nice package. I am curious about accomplish two things:

1. Removing the comments.
2. Putting opening parenthesis.

I am not sure if this is possible now or am I missing something?

**Comment by analyticsseo** [comment]
@Trudko 

you should be able to define your own template in the settings.

I think atom changed its settings api and you no longer have that option, I will fix it soon

thanks

**Comment by francodacosta** [comment]
@Trudko

you should be able to define your own template in the settings.

I think atom changed its settings api and you no longer have that option, I will fix it soon

thanks

**Comment by Trudko** [comment]
@francodacosta Thank you for quick answer! I wasn't also sure how exactly I should define my own template. It seems like you use your own kind of mini template, don't you?

**Comment by francodacosta** [comment]
@Trudko yes I do. But you should be able to change it in the package settings.

I will try to fix this today or tomorrow

**Comment by francodacosta** [comment]
@Trudko the settings should be back

**Comment by francodacosta** [comment]
@Trudko Atom does not support text areas in the settings. So changing the templates is not a good experience.

I'm adding a basic template editor to the package, should be ready this weekend

**Comment by Trudko** [comment]
Sounds great, how about to integrate it with snippet maybe?

**Comment by analyticsseo** [comment]
@Trudko, maybe.

Can you explain me how you see it working?

**Comment by francodacosta** [comment]
@Trudko, maybe.

Can you explain me how you see it working?

**Comment by Trudko** [comment]
Well how about you could have default template but you can also set name of snippet to be used. Theyn you would create separate snippet for getters and setters package and you would put package custom variables  like scope / variable etc.

**Comment by Trudko** [comment]
Any update on this?

**Comment by analyticsseo** [comment]
@Trudko I don;t think integration with code snippets will happen any time soon

maybe if someone contributes a pull request ...

**Comment by francodacosta** [comment]
@Trudko I don;t think integration with code snippets will happen any time soon

maybe if someone contributes a pull request ...
